### ISSUE TITLE
Add tests to illustrate exposing custom Swift types to the Lua VM

### ISSUE THREAD

**Issue by BenziAhamed** [sdegutis/lua4swift#2]
It would be nice to understand how to go about exposing custom types defined in Swift to the Lua VM. 

For example, how might one expose the Note class and its properties and functions?

```
class Note {
    var title = ""
    var contents = ""
    var tag = ""
    init(title:String, contents:String) {
       self.title = title
       self.contents = contents
    }
   func setTag(tag:String) {
       self.tag = tag
   }
    func reset() {
        self.title = ""
        self.contents = ""
        self.tag = ""
    }
}
```

**Comment by sdegutis** [comment]
Good question!

I forgot how to do it.

I think it has something to do with either instantiating `Lua.CustomType` (defined in `Lua/Userdata.swift`) or extending a type to conform to it.

**Comment by BenziAhamed** [comment]
I think I figured it out. Can you have a loot at this pull request? #3
