### ISSUE TITLE
Multi Lua files issue

### ISSUE THREAD

**Issue by ArthurXu424** [sdegutis/lua4swift#8]
Thank you for the sharing, I am a little confused about the binding you wrote in `What do you mean by "bindings"?`
this means we can get Lua data or call Lua functions from swift, what if i have multi Lua files in my project? how can unwrap the one i need? how can i write data or arguments to the right Lua file?particularly function with same name.

**Comment by sdegutis** [comment]
This project is for embedding a Lua engine and executing Lua code, allowing data to be easily shared between Lua and Swift. How you get Lua files into the engine is a concern separate from this project, and is usually as simple as using Swift's standard library to load files from the file system and run them in Lua. There is one convenience Swift function that takes a `URL` and loads the code from that, but that's it. The rest of Lua conventions about `require(...)` apply as usual.
